### ISSUE TITLE
Slot Save Editor Feature Request

### ISSUE THREAD

**Issue by SasorizaTsugare** [OnyxdevSoftware/rogueEditor#4]
Im not sure I am putting this in the right place but please add an in UI ability to add/remove items to a slot save. Its currently difficult to look up all of the relevant information needed to add new items to a save from the game repo.

**Comment by OnyxdevSoftware** [comment]
For now, i'm not going to implement any UI.
This is to maintain compatibility for different operating systems.

**Comment by SasorizaTsugare** [comment]
I didnt mean a more advanced GUI but an additional menu to the current text UI for messing items for the individual save slots.
